const TILE = 32,
  MAP_W = 192,
  MAP_H = 160,
  TICK_MS = 600;
const ITEMS = {
  coins: { name: 'Coins', icon: '\u25CF', stack: true },
  bread: { name: 'Bread', icon: '\u25B0', heal: 4 },
  stew: { name: 'Pineholt stew', icon: '\u25D2', stack: true, heal: 9 },
  rod: { name: 'Fishing rod', icon: '\u2301' },
  bait: { name: 'Fishing bait', icon: '\u2022', stack: true },
  rawFish: { name: 'Raw riverfish', icon: '\u25D6', stack: true },
  rawEel: { name: 'Raw marsh eel', icon: '\u2248', stack: true },
  marshEel: { name: 'Cooked marsh eel', icon: '\u223F', stack: true, heal: 8, cure: 2 },
  rawMeat: { name: 'Raw boar meat', icon: '\u25D3', stack: true },
  cookedMeat: { name: 'Cooked boar meat', icon: '\u25D1', stack: true, heal: 7 },
  snare: { name: 'Wooden snare', icon: '\u2311' },
  rabbitMeat: { name: 'Raw rabbit', icon: '\u25D4', stack: true },
  roastRabbit: { name: 'Roast rabbit', icon: '\u25D5', stack: true, heal: 8 },
  rabbitFur: { name: 'Rabbit fur', icon: '\u224B', stack: true },
  fish: { name: 'Cooked riverfish', icon: '\u25D7', stack: true, heal: 6 },
  bones: { name: 'Bones', icon: 'X', stack: true },
  hide: { name: 'Goblin hide', icon: '\u25C6', stack: true },
  sword: { name: 'Bronze sword', icon: '\u2020', attack: 2 },
  shortbow: { name: 'Shortbow', icon: ')', ranged: 3, range: 5 },
  arrows: { name: 'Bronze arrows', icon: '\u2192', stack: true },
  emberStaff: { name: 'Ember staff', icon: '\u0192', magic: 3, range: 6 },
  emberRune: { name: 'Ember rune', icon: '\u2727', stack: true },
  steelSword: { name: 'Pineholt blade', icon: '\u2021', attack: 4 },
  pickaxe: { name: 'Bronze pickaxe', icon: '\u2692' },
  ironPickaxe: { name: 'Iron pickaxe', icon: '\u26CF' },
  hatchet: { name: 'Bronze hatchet', icon: '\u2320' },
  knife: { name: 'Carving knife', icon: '\u25B6' },
  tinderbox: { name: 'Tinderbox', icon: '\u25A4' },
  copperOre: { name: 'Copper ore', icon: '\u25CF', stack: true },
  ironOre: { name: 'Iron ore', icon: '\u25CF', stack: true },
  bronzeBar: { name: 'Bronze bar', icon: '\u25AC', stack: true },
  ironBar: { name: 'Iron bar', icon: '\u25AC', stack: true },
  forgedSword: { name: 'Iron longsword', icon: '\u2020', attack: 5 },
  shield: { name: 'Bronze shield', icon: '\u25D0', defence: 2, slot: 'shield' },
  ironShield: { name: 'Iron kiteshield', icon: '\u25D0', defence: 4, slot: 'shield' },
  roadBuckler: { name: 'Frostmere buckler', icon: '\u25D2', defence: 3, slot: 'shield' },
  bronzeArmor: { name: 'Bronze platebody', icon: '\u25A3', defence: 3, slot: 'armor' },
  bronzeHelmet: { name: 'Bronze helmet', icon: '\u26D1', defence: 1, slot: 'helmet' },
  bronzeLegs: { name: 'Bronze platelegs', icon: '\u26BF', defence: 2, slot: 'legs' },
  ironArmor: { name: 'Iron platebody', icon: '\u25A3', defence: 4, slot: 'armor' },
  ironHelmet: { name: 'Iron helmet', icon: '\u26D1', defence: 2, slot: 'helmet' },
  ironLegs: { name: 'Iron platelegs', icon: '\u26BF', defence: 3, slot: 'legs' },
  leatherBody: { name: 'Leather body', icon: '\u25A7', defence: 3, slot: 'armor' },
  silkRobe: { name: 'Cave-silk robe', icon: '\u25A8', defence: 3, slot: 'armor' },
  wardenCloak: { name: 'Warden cloak', icon: '\u2666', defence: 6, slot: 'armor' },
  willowMantle: { name: 'Thornwood mantle', icon: '\u2660', defence: 4, slot: 'armor' },
  furGloves: { name: 'Rabbit-fur gloves', icon: '\u222A', defence: 2, slot: 'gloves' },
  logs: { name: 'Logs', icon: '\u25A5', stack: true },
  cabbageSeed: { name: 'Cabbage seed', icon: '\u2022', stack: true },
  cabbage: { name: 'Cabbage', icon: '\u25C9', stack: true, heal: 3 },
  herb: { name: 'Wild herb', icon: '\u2663', stack: true },
  vial: { name: 'Empty vial', icon: '\u25C7', stack: true },
  healingPotion: { name: 'Minor healing potion', icon: '\u25C8', stack: true, heal: 8 },
  energyPotion: { name: 'Run energy potion', icon: '\u25C9', stack: true, energy: 35 },
  key: { name: 'Barrow key', icon: '\u26BF' },
  relic: { name: 'Ember relic', icon: '\u2726' },
  ashenShard: { name: 'Ashen shard', icon: '\u2725', stack: true },
  ashenGuard: { name: 'Ashen guard', icon: '\u25D0', defence: 5, slot: 'shield' },
  barrowLantern: { name: 'Barrow lantern', icon: '\u2600' },
  bogMoss: { name: 'Bog moss', icon: '\u2663', stack: true },
  antidote: { name: 'Marsh antidote', icon: '\u25C8', stack: true },
  mireCharm: { name: 'Sablemarsh charm', icon: '\u222A', defence: 3, slot: 'gloves' },
  explorerCape: { name: 'Emberfall explorer cape', icon: '\u2666', defence: 5, slot: 'armor' },
  spiderSilk: { name: 'Cave silk', icon: '\u2318', stack: true },
  // --- Combat depth: smithing materials ---
  coal: { name: 'Coal', icon: '\u25cf', stack: true },
  mithrilOre: { name: 'Mithril ore', icon: '\u25cf', stack: true },
  steelBar: { name: 'Steel bar', icon: '\u25ac', stack: true },
  mithrilBar: { name: 'Mithril bar', icon: '\u25ac', stack: true },
  emberIngot: { name: 'Emberforged ingot', icon: '\u2726', stack: true },
  // --- Tiered weapons (speed = ticks per attack; req = level to wield) ---
  ironDagger: { name: 'Iron dagger', icon: '\u2020', attack: 3, speed: 2, req: 5, reqSkill: 'Attack', spec: 'double' },
  steelLongsword: { name: 'Steel longsword', icon: '\u2020', attack: 7, speed: 4, req: 10, reqSkill: 'Attack' },
  steelBattleaxe: { name: 'Steel battleaxe', icon: '\u2352', attack: 9, speed: 6, req: 12, reqSkill: 'Attack', spec: 'power' },
  mithrilScimitar: { name: 'Mithril scimitar', icon: '\u2021', attack: 11, speed: 3, req: 20, reqSkill: 'Attack', spec: 'double' },
  emberGreatsword: { name: 'Emberforged greatsword', icon: '\u2352', attack: 16, speed: 6, req: 30, reqSkill: 'Attack', spec: 'power' },
  // --- Tiered armour ---
  steelPlatebody: { name: 'Steel platebody', icon: '\u25a3', defence: 6, slot: 'armor', req: 10, reqSkill: 'Defence' },
  mithrilPlatebody: { name: 'Mithril platebody', icon: '\u25a3', defence: 8, slot: 'armor', req: 20, reqSkill: 'Defence' },
  emberPlatebody: { name: 'Emberforged platebody', icon: '\u25a3', defence: 11, slot: 'armor', req: 30, reqSkill: 'Defence' },
  // --- Tiered shields ---
  steelKite: { name: 'Steel kiteshield', icon: '\u25d0', defence: 5, slot: 'shield', req: 10, reqSkill: 'Defence' },
  mithrilKite: { name: 'Mithril kiteshield', icon: '\u25d0', defence: 7, slot: 'shield', req: 20, reqSkill: 'Defence' },
  emberTower: { name: 'Emberforged tower shield', icon: '\u25d0', defence: 10, slot: 'shield', req: 30, reqSkill: 'Defence' },
  // --- Gloves ---
  steelGauntlets: { name: 'Steel gauntlets', icon: '\u222a', defence: 4, slot: 'gloves', req: 10, reqSkill: 'Defence' },
};
// Attack speed + wield requirements for the original weapons/armour
Object.assign(ITEMS.sword, { speed: 4, req: 1, reqSkill: 'Attack' });
Object.assign(ITEMS.steelSword, { speed: 4, req: 5, reqSkill: 'Attack', spec: 'power' });
Object.assign(ITEMS.forgedSword, { speed: 4, req: 10, reqSkill: 'Attack' });
Object.assign(ITEMS.shortbow, { speed: 4, req: 1, reqSkill: 'Ranged' });
Object.assign(ITEMS.emberStaff, { speed: 5, req: 1, reqSkill: 'Magic' });
Object.assign(ITEMS.shield, { req: 1, reqSkill: 'Defence' });
Object.assign(ITEMS.bronzeArmor, { req: 1, reqSkill: 'Defence' });
Object.assign(ITEMS.bronzeHelmet, { req: 1, reqSkill: 'Defence' });
Object.assign(ITEMS.bronzeLegs, { req: 1, reqSkill: 'Defence' });
Object.assign(ITEMS.roadBuckler, { req: 5, reqSkill: 'Defence' });
Object.assign(ITEMS.ironArmor, { req: 10, reqSkill: 'Defence' });
Object.assign(ITEMS.ironHelmet, { req: 10, reqSkill: 'Defence' });
Object.assign(ITEMS.ironLegs, { req: 10, reqSkill: 'Defence' });
Object.assign(ITEMS.ironShield, { req: 10, reqSkill: 'Defence' });
Object.assign(ITEMS.leatherBody, { req: 1, reqSkill: 'Defence' });
Object.assign(ITEMS.silkRobe, { req: 1, reqSkill: 'Defence' });
Object.assign(ITEMS.willowMantle, { req: 8, reqSkill: 'Defence' });
Object.assign(ITEMS.wardenCloak, { req: 20, reqSkill: 'Defence' });
Object.assign(ITEMS.ashenGuard, { req: 15, reqSkill: 'Defence' });
Object.assign(ITEMS.explorerCape, { req: 10, reqSkill: 'Defence' });
Object.entries({
  bread: 3,
  stew: 7,
  rod: 12,
  bait: 1,
  rawFish: 2,
  rawEel: 5,
  marshEel: 13,
  rawMeat: 4,
  cookedMeat: 9,
  snare: 18,
  rabbitMeat: 5,
  roastRabbit: 11,
  rabbitFur: 8,
  fish: 5,
  bones: 1,
  hide: 8,
  sword: 22,
  shortbow: 32,
  arrows: 1,
  emberStaff: 40,
  emberRune: 2,
  steelSword: 60,
  pickaxe: 18,
  ironPickaxe: 60,
  hatchet: 15,
  knife: 12,
  tinderbox: 5,
  copperOre: 3,
  ironOre: 7,
  bronzeBar: 8,
  ironBar: 18,
  forgedSword: 90,
  shield: 30,
  ironShield: 85,
  roadBuckler: 85,
  bronzeArmor: 55,
  bronzeHelmet: 25,
  bronzeLegs: 40,
  ironArmor: 110,
  ironHelmet: 70,
  ironLegs: 90,
  leatherBody: 70,
  silkRobe: 95,
  wardenCloak: 250,
  willowMantle: 140,
  furGloves: 65,
  logs: 3,
  cabbageSeed: 2,
  cabbage: 4,
  herb: 6,
  vial: 2,
  healingPotion: 22,
  energyPotion: 28,
  ashenShard: 30,
  ashenGuard: 420,
  barrowLantern: 300,
  bogMoss: 12,
  antidote: 30,
  mireCharm: 120,
  explorerCape: 350,
  spiderSilk: 10,
  coal: 5,
  mithrilOre: 35,
  steelBar: 25,
  mithrilBar: 55,
  emberIngot: 200,
  ironDagger: 40,
  steelLongsword: 120,
  steelBattleaxe: 180,
  mithrilScimitar: 320,
  emberGreatsword: 1200,
  steelPlatebody: 200,
  mithrilPlatebody: 450,
  emberPlatebody: 1400,
  steelKite: 160,
  mithrilKite: 380,
  emberTower: 1100,
  steelGauntlets: 120,
}).forEach(([id, value]) => (ITEMS[id].value = value));
const NPCS = [
  { id: 'elowen', name: 'Guide Elowen', x: 171, y: 40, color: '#c5a44e', role: 'Greenrest guide' },
  {
    id: 'king',
    name: 'King Aldric',
    x: 171,
    y: 20,
    color: '#8a6a2e',
    role: 'King of Greenrest',
    dialogue:
      'The Wardens gave their names to hold the fire below, and I gave mine to hold this realm above. Different oaths, same weight. Walk safely, ember-touched — Greenrest remembers what it owes the old bloodline, even if you do not.',
  },
  {
    id: 'yara',
    name: 'Steward Yara',
    x: 171,
    y: 29,
    color: '#5c6b7a',
    role: "Aldric's steward",
    dialogue:
      "I have counted every wagon that never arrived, and I have stopped believing it is bandits. Bandits do not leave the ash undisturbed. Something is being carried out of the wastes, not stolen along a road.",
  },
  {
    id: 'corvin',
    name: 'Corvin',
    x: 183,
    y: 46,
    color: '#6a4f9b',
    role: 'Arcane trader',
    dialogue:
      "Ember runes don't like to sit still in a pack — mind you keep them dry and away from open flame. Not that flame is much of a stranger to you, is it, Wanderer.",
  },
  { id: 'alaric', name: 'Alaric', x: 174, y: 57, color: '#a86c3d', role: 'General store trader' },
  { id: 'murphy', name: 'Fisher Murphy', x: 147, y: 83, color: '#4f83a4', role: 'Fishing supplier' },
  { id: 'banker', name: 'Banker Willa', x: 119, y: 11, color: '#795b9b', role: 'Greenrest bank' },
  { id: 'rowan', name: 'Captain Rowan', x: 87, y: 67, color: '#8f4d3f', role: 'Pineholt watch-captain' },
  { id: 'tamsin', name: 'Tamsin', x: 104, y: 67, color: '#b77943', role: 'Pineholt innkeeper' },
  {
    id: 'fen',
    name: 'Bard Fen',
    x: 99,
    y: 74,
    color: '#6f568c',
    role: 'Travelling bard',
    wander: 2,
    dialogue:
      'Every road remembers its travellers. The Ashen Barrow song has gained a new verse since you arrived.',
  },
  { id: 'mira', name: 'Scholar Mira', x: 50, y: 68, color: '#665ca5', role: 'Warden loremaster' },
  { id: 'torren', name: 'Torren', x: 119, y: 67, color: '#6f7f8f', role: 'Emberwright smith' },
  {
    id: 'bren',
    name: 'Guard Bren',
    x: 136,
    y: 37,
    color: '#687b8d',
    role: 'Greenrest guard',
    wander: 3,
    dialogue:
      'The seals below weaken, and the wastes spill their creatures over the land. I pay good coin for every beast you put down — call it keeping the old watch.',
  },
  {
    id: 'jory',
    name: 'Farmer Jory',
    x: 45,
    y: 52,
    color: '#8b7042',
    role: 'Greenrest farmer',
    wander: 4,
    pickpocket: true,
    dialogue: 'The vale fields feed the whole region. Mind the wolves up in the pines.',
  },
  {
    id: 'nessa',
    name: 'Nessa',
    x: 94,
    y: 73,
    color: '#a16d78',
    role: 'Pineholt villager',
    wander: 3,
    pickpocket: true,
    dialogue:
      "Captain Rowan's line has watched the north road since the Binding. We sleep easier for it — most nights.",
  },
  { id: 'willow', name: 'Elder Willow', x: 111, y: 64, color: '#7c9760', role: 'Thornwood elder' },
  { id: 'orin', name: 'Hunter Orin', x: 164, y: 65, color: '#806348', role: 'Thornwood hunter' },
  {
    id: 'maeve',
    name: 'Maeve',
    x: 153,
    y: 74,
    color: '#7996a2',
    role: 'Thornwood villager',
    wander: 3,
    pickpocket: true,
    dialogue:
      'The boars root near the eastern hedges. Orin pays attention to anyone carrying a bow.',
  },
  {
    id: 'vale',
    name: 'Scout Vale',
    x: 12,
    y: 36,
    color: '#557c68',
    role: 'Warden watcher',
    wander: 3,
    pickpocket: true,
    dialogue:
      'I watch the Barrow door so the world need not. The ruins glow after sunset now — the seal is thinning, and I am the last set to watch it.',
  },
  {
    id: 'harker',
    name: 'Harker',
    x: 20,
    y: 11,
    color: '#7a6a52',
    role: "Kessa's currier",
    dialogue: 'Move along. I have got nothing for you.',
  },
  { id: 'mara', name: 'Mara', x: 88, y: 18, color: '#a36f45', role: 'Frostmere provisioner' },
  {
    id: 'edric',
    name: 'Brother Edric',
    x: 159,
    y: 85,
    color: '#8a7aa3',
    role: 'Frostmere healer',
    dialogue: 'Every traveller deserves a warm fire before crossing the snowfields.',
  },
  { id: 'sable', name: 'Healer Sable', x: 10, y: 122, color: '#56806a', role: 'Sablemarsh healer' },
  {
    id: 'fenwick',
    name: 'Fenwick',
    x: 22,
    y: 114,
    color: '#8a6d47',
    role: 'Sablemarsh trader',
    dialogue: 'Dry boots cost extra in Sablemarsh. Everything else is fairly priced.',
  },
  {
    id: 'kessa',
    name: 'Kessa',
    x: 117,
    y: 67,
    color: '#a4523f',
    role: 'The Ashwright',
    dialogue: 'Mind your own fire, Wanderer, and I will mind mine.',
  },
  {
    id: 'pell',
    name: 'Pell',
    x: 102,
    y: 68,
    color: '#c99a5b',
    role: 'Pineholt runner',
    wander: 3,
    dialogue: 'The old Warden stories used to be just stories. Now you are standing right here.',
  },
];
const NPC_AMBIENT = {
  elowen: [
    'The Vale is the green heart — farthest from the wound below.',
    'You arrived the night the old tablets glowed. That was not chance.',
  ],
  king: [
    'A crown is just a promise other people can see.',
    'Every scout who rides for the wastes gets my thanks, whether they know it or not.',
  ],
  yara: [
    'Three wagons this month. Full loads of ember-rune, gone between Cinderforge and the road.',
    'I served the last steward and the one before. I know the difference between a bad season and a plan.',
  ],
  harker: [
    'Keep it quiet. I mean it.',
    'The wind out here carries further than you would think.',
  ],
  corvin: [
    'Every rune I sell was ground from stone that remembers the Emberfall. Handle them with respect.',
    'The old Warden scholars distilled the Ember into runes so lesser hands could still touch its heat, safely. Mostly safely.',
  ],
  alaric: [
    'Supplies for the wastes road, friend — you will need them.',
    'My gran swore the sky once burned. I used to laugh at her.',
  ],
  murphy: [
    'The water tastes of ash some mornings now. Never used to.',
    'Even the fish feel it stirring, down under the earth.',
  ],
  rowan: [
    'My line has watched this northern road since the Binding.',
    'Things climb down out of the Ashfall. Keep your blade near.',
  ],
  tamsin: [
    'Warm beds and warmer stew — small mercies while the seals hold.',
    'Sing an old Barrow verse and the hearth burns brighter, they say.',
  ],
  bren: [
    'The failing seals loose what I pay good folk to cull.',
    'Contracts for capable hands — the wastes breed more each week.',
  ],
  jory: [
    'Good soil, so long as the ash stays north of my fences.',
    'The wolves come down from the pines, fleeing something worse.',
  ],
  willow: [
    'The three tablets survive here as ballads. Listen close.',
    'The Wardens gave everything they were to shut that door.',
  ],
  orin: [
    'I track beasts that flee the ash into my woods.',
    'Aim true — the prey runs angrier than it once did.',
  ],
  maeve: [
    'Boars root by the hedge, running from the wastes.',
    'They say the fire below is waking. I try not to dwell on it.',
  ],
  mira: [
    'The Barrow runes are changing. The seals are weakening.',
    'You are ember-touched, Wanderer. The old Warden blood, I am nearly sure.',
  ],
  torren: [
    'Ember-heat forges the finest steel — and the mountain gives more each day.',
    'Cinderforge sits closest to the buried fire. We feel every tremor.',
  ],
  vale: [
    'The Barrow ruins glow after sunset. The seal is thinning.',
    'I watch the door so the rest of the world need not.',
  ],
  mara: [
    "The cold holds the Ember's heat at bay — for now.",
    'Provisions before the snowfields, traveller. Frostmere endures.',
  ],
  edric: [
    'I say the prayers that the three seals hold another year.',
    'A warm fire, and a word for the Wardens who gave theirs.',
  ],
  sable: [
    "The marsh-fever is the Ember's sickness, seeping up through the water.",
    'Bog moss dulls the ache. A true cure it is not.',
  ],
  fenwick: [
    'Dry goods in a drowning marsh — and the fever only worsens.',
    'Mind the boglings; they crawl up thicker every season.',
  ],
  kessa: [
    'Mira would have you believe there is only one way to hold a fire. There is not.',
    'Nine years I have studied what she buried. Nine years, and she still calls it heresy.',
  ],
  pell: [
    'I want to see the Barrow myself someday. Just — not the parts with the Warden in them.',
    'My mother says I ask too many questions about ember-touched Wanderers. She is probably right.',
  ],
};
const MONSTER_TYPES = {
  rat: {
    name: 'Giant rat',
    color: '#776753',
    hp: 4,
    maxHit: 1,
    xp: 8,
    drops: [
      ['bones', 1, 1],
      ['coins', 2, 7],
    ],
  },
  goblin: {
    name: 'Goblin raider',
    color: '#678847',
    hp: 8,
    maxHit: 2,
    xp: 14,
    drops: [
      ['bones', 1, 1],
      ['coins', 5, 14],
      ['hide', 1, 1],
      ['herb', 1, 1, 0.25],
      ['emberRune', 1, 3, 0.4],
    ],
  },
  wolf: {
    name: 'Grey wolf',
    color: '#66727a',
    hp: 11,
    maxHit: 2,
    xp: 18,
    drops: [
      ['bones', 1, 1],
      ['coins', 6, 15],
      ['herb', 1, 1, 0.3],
    ],
  },
  skeleton: {
    name: 'Barrow skeleton',
    color: '#c9c3a4',
    hp: 13,
    maxHit: 3,
    xp: 24,
    drops: [
      ['bones', 1, 2],
      ['coins', 8, 20],
      ['emberRune', 2, 5, 0.55],
    ],
  },
  guardian: {
    name: 'Barrow guardian',
    color: '#d4c99f',
    hp: 16,
    maxHit: 3,
    xp: 30,
    drops: [
      ['bones', 1, 2],
      ['coins', 12, 24],
      ['emberRune', 3, 6, 0.65],
    ],
  },
  boar: {
    name: 'Wild boar',
    color: '#7b543e',
    hp: 9,
    maxHit: 2,
    xp: 16,
    drops: [
      ['bones', 1, 1],
      ['coins', 4, 11],
      ['rawMeat', 1, 1, 0.75],
    ],
  },
  bandit: {
    name: 'Road bandit',
    color: '#8a553c',
    hp: 12,
    maxHit: 3,
    xp: 22,
    drops: [
      ['coins', 10, 28],
      ['bread', 1, 2, 0.55],
      ['herb', 1, 1, 0.3],
    ],
  },
  bat: {
    name: 'Ash bat',
    color: '#6e536f',
    hp: 7,
    maxHit: 2,
    xp: 15,
    drops: [
      ['bones', 1, 1],
      ['coins', 3, 10],
      ['emberRune', 1, 2, 0.5],
    ],
  },
  bogling: {
    name: 'Bogling',
    color: '#46684b',
    hp: 10,
    maxHit: 2,
    xp: 19,
    drops: [
      ['bogMoss', 1, 1],
      ['coins', 4, 13],
      ['herb', 1, 1, 0.35],
    ],
  },
  spider: {
    name: 'Cave spider',
    color: '#5a3855',
    hp: 10,
    maxHit: 3,
    xp: 20,
    drops: [
      ['spiderSilk', 1, 2],
      ['coins', 4, 12],
    ],
  },
  warden: {
    name: 'Ashen Warden',
    color: '#8d503d',
    hp: 30,
    maxHit: 4,
    xp: 90,
    hasSigils: true,
    drops: [
      ['ashenShard', 1, 2],
      ['coins', 75, 120],
      ['emberIngot', 1, 2, 0.5],
    ],
  },
  ashwrightRenn: {
    name: 'Ashwright Renn',
    color: '#7a4a6b',
    hp: 24,
    maxHit: 5,
    xp: 55,
    attackSpeed: 3,
    drops: [
      ['coins', 20, 45],
      ['coal', 1, 3, 0.3],
      ['emberIngot', 1, 1, 0.15],
    ],
  },
  unboundConstruct: {
    name: 'Unbound Construct',
    color: '#d5622a',
    hp: 32,
    maxHit: 5,
    xp: 110,
    boss: true,
    hasSigils: true,
    attackSpeed: 3,
    drops: [
      ['coins', 80, 150],
      ['emberIngot', 1, 2, 0.45],
      ['ashenGuard', 1, 1, 0.3],
    ],
  },
  direWolf: {
    name: 'Dire wolf',
    color: '#4a525a',
    hp: 20,
    maxHit: 4,
    xp: 40,
    drops: [
      ['bones', 1, 1],
      ['coins', 10, 24],
      ['coal', 1, 3, 0.4],
      ['mithrilOre', 1, 1, 0.12],
    ],
  },
  goblinWarlord: {
    name: 'Goblin warlord',
    color: '#3f6b2c',
    hp: 45,
    maxHit: 5,
    xp: 120,
    boss: true,
    attackSpeed: 3,
    drops: [
      ['coins', 60, 140],
      ['steelBar', 2, 4],
      ['steelLongsword', 1, 1, 0.2],
      ['emberIngot', 1, 1, 0.15],
    ],
  },
  cinderFiend: {
    name: 'Cinder fiend',
    color: '#c0542a',
    hp: 28,
    maxHit: 5,
    xp: 60,
    drops: [
      ['coins', 14, 30],
      ['coal', 2, 4, 0.5],
      ['mithrilOre', 1, 2, 0.2],
      ['emberIngot', 1, 1, 0.1],
    ],
  },
  frostTroll: {
    name: 'Frost troll',
    color: '#7fa3c4',
    hp: 34,
    maxHit: 5,
    xp: 72,
    drops: [
      ['bones', 1, 2],
      ['coins', 18, 36],
      ['mithrilOre', 1, 2, 0.25],
      ['emberIngot', 1, 1, 0.12],
    ],
  },
  cinderColossus: {
    name: 'Cinder Colossus',
    color: '#e0631f',
    hp: 65,
    maxHit: 6,
    xp: 220,
    boss: true,
    attackSpeed: 4,
    drops: [
      ['coins', 150, 300],
      ['emberIngot', 2, 4],
      ['emberGreatsword', 1, 1, 0.12],
      ['emberPlatebody', 1, 1, 0.1],
    ],
  },
};
const MONSTER_SPAWNS = [
  ['rat', 84, 31],
  ['rat', 110, 29],
  ['wolf', 76, 35],
  ['goblin', 90, 53],
  ['goblin', 104, 53],
  ['goblin', 86, 87],
  ['goblin', 106, 87],
  ['wolf', 82, 53],
  ['wolf', 110, 55],
  ['wolf', 80, 91],
  ['boar', 144, 91],
  ['boar', 168, 87],
  ['direWolf', 82, 85],
  ['direWolf', 112, 87],
  ['goblinWarlord', 98, 91],
  ['frostTroll', 100, 11],
  ['frostTroll', 120, 31],
  // Road bandits — the road stretch around (72, 98), matching "The Broken Road" side quest.
  ['bandit', 79, 103],
  ['bandit', 77, 105],
  ['bandit', 74, 107],
  ['bandit', 72, 108],
  // Kessa's hidden camp — far NW wastes, "The Ashwright's Gambit" quest.
  ['ashwrightRenn', 16, 10],
  ['unboundConstruct', 18, 12],
  ['rat', 159, 10],
  ['rat', 167, 9],
  ['rat', 176, 10],
  ['rat', 183, 9],
  // Ashen Barrow — 3x3 chamber grid, cells 0-7 (see BARROW_ROOMS in data.js for the cell map)
  ['guardian', 9, 74],
  ['guardian', 15, 73],
  ['guardian', 24, 73],
  ['skeleton', 9, 80],
  ['guardian', 15, 80],
  ['bat', 24, 80],
  ['spider', 9, 87],
  ['guardian', 15, 87],
  // Ashen Barrow — cell 8, the Warden's chamber (always last)
  ['warden', 24, 88],
  // Ashfall Wastes surface — the guardian that carries the quest seal-key
  ['guardian', 9, 60],
  ['goblin', 78, 59],
  ['goblin', 88, 55],
  ['wolf', 61, 29],
  ['wolf', 67, 22],
  ['wolf', 69, 32],
  ['frostTroll', 35, 24],
  ['frostTroll', 36, 31],
  ['frostTroll', 48, 21],
  ['cinderColossus', 83, 134],
  ['cinderFiend', 91, 134],
  ['goblinWarlord', 165, 83],
  ['goblinWarlord', 165, 8],
  ['goblinWarlord', 42, 89],
  ['skeleton', 71, 131],
  ['skeleton', 128, 99],
  ['skeleton', 2, 49],
  ['skeleton', 1, 45],
  ['bat', 2, 65],
  ['bat', 4, 46],
  ['bat', 1, 40],
  ['bogling', 129, 23],
  ['bogling', 44, 146],
  ['bogling', 36, 139],
  ['bogling', 38, 129],
  ['bogling', 48, 134],
  ['bogling', 38, 113],
  ['bogling', 32, 112],
  ['bogling', 44, 110],
  ['direWolf', 128, 135],
  ['direWolf', 57, 8],
  ['direWolf', 38, 6],
  ['direWolf', 39, 15],
  ['direWolf', 50, 8],
];
const SHOPS = {
  general: [
    ['bread', 6],
    ['sword', 45],
    ['shortbow', 65],
    ['arrows', 2],
    ['emberStaff', 80],
    ['emberRune', 3],
    ['shield', 55],
    ['hatchet', 30],
    ['tinderbox', 10],
    ['cabbageSeed', 3],
    ['vial', 4],
  ],
  fishing: [
    ['rod', 20],
    ['bait', 1],
  ],
  magic: [
    ['emberStaff', 80],
    ['emberRune', 3],
  ],
  hunter: [
    ['snare', 35],
    ['knife', 25],
    ['shortbow', 60],
    ['arrows', 2],
    ['leatherBody', 125],
  ],
  smith: [
    ['pickaxe', 35],
    ['ironPickaxe', 120],
  ],
  mirehaven: [
    ['bread', 5],
    ['vial', 3],
    ['herb', 8],
    ['antidote', 32],
    ['healingPotion', 24],
    ['energyPotion', 30],
    ['tinderbox', 8],
  ],
  embercross: [
    ['bread', 5],
    ['stew', 10],
    ['healingPotion', 25],
    ['energyPotion', 32],
    ['emberRune', 3],
    ['vial', 3],
  ],
};
const FISH_SPOTS = [
  { id: 'fish2', x: 143, y: 19, name: 'River fishing spot', item: 'rawFish', catchName: 'riverfish', level: 1, xp: 12, chance: 0.8 },
  { id: 'fish3', x: 140, y: 19, name: 'River fishing spot', item: 'rawFish', catchName: 'riverfish', level: 1, xp: 12, chance: 0.8 },
  { id: 'fish4', x: 141, y: 17, name: 'River fishing spot', item: 'rawFish', catchName: 'riverfish', level: 1, xp: 12, chance: 0.8 },
  { id: 'fish5', x: 149, y: 88, name: 'River fishing spot', item: 'rawFish', catchName: 'riverfish', level: 1, xp: 12, chance: 0.8 },
  { id: 'fish6', x: 152, y: 88, name: 'River fishing spot', item: 'rawFish', catchName: 'riverfish', level: 1, xp: 12, chance: 0.8 },
  { id: 'fish7', x: 148, y: 88, name: 'River fishing spot', item: 'rawFish', catchName: 'riverfish', level: 1, xp: 12, chance: 0.8 },
  { id: 'fish8', x: 147, y: 87, name: 'River fishing spot', item: 'rawFish', catchName: 'riverfish', level: 1, xp: 12, chance: 0.8 },
  { id: 'fish9', x: 5, y: 113, name: 'Marsh eel spot', item: 'rawEel', catchName: 'marsh eel', level: 3, xp: 22, chance: 0.72 },
  { id: 'fish10', x: 7, y: 111, name: 'Marsh eel spot', item: 'rawEel', catchName: 'marsh eel', level: 3, xp: 22, chance: 0.72 },
  { id: 'fish11', x: 2, y: 110, name: 'Marsh eel spot', item: 'rawEel', catchName: 'marsh eel', level: 3, xp: 22, chance: 0.72 },
  { id: 'fish12', x: 3, y: 108, name: 'Marsh eel spot', item: 'rawEel', catchName: 'marsh eel', level: 3, xp: 22, chance: 0.72 },
];
const HUNT_SPOTS = [
  { id: 'burrow1', x: 140, y: 81, name: 'Rabbit burrow', level: 1, xp: 20 },
  { id: 'burrow2', x: 166, y: 83, name: 'Rabbit burrow', level: 1, xp: 20 },
];
const ROCKS = [
  { id: 'rock1', x: 124, y: 5, ore: 'copperOre', name: 'Copper rock', level: 1, xp: 12, color: '#b87343' },
  { id: 'rock2', x: 126, y: 5, ore: 'copperOre', name: 'Copper rock', level: 1, xp: 12, color: '#b87343' },
  { id: 'rock3', x: 126, y: 7, ore: 'copperOre', name: 'Copper rock', level: 1, xp: 12, color: '#b87343' },
  { id: 'rock4', x: 127, y: 8, ore: 'ironOre', name: 'Iron rock', level: 5, xp: 22, color: '#8d8174' },
  { id: 'rock5', x: 127, y: 6, ore: 'ironOre', name: 'Iron rock', level: 5, xp: 22, color: '#8d8174' },
  { id: 'coal1', x: 123, y: 7, ore: 'coal', name: 'Coal rock', level: 10, xp: 28, color: '#2c2c2c' },
  { id: 'mithril1', x: 120, y: 9, ore: 'mithrilOre', name: 'Mithril rock', level: 20, xp: 55, color: '#4a6b8a' },
];
const FORGE = { x: 104, y: 15, name: 'Cinderforge anvil' };
const FURNACE = { x: 107, y: 15, name: 'Cinderforge furnace' };
const ALTAR = { x: 49, y: 72, name: 'Frostmere altar' };
const WORKBENCH = { x: 101, y: 15, name: 'Greenrest crafting bench' };
const CAULDRON = { x: 101, y: 82, name: 'Sablemarsh brewing cauldron' };
const SIGNPOSTS = [
  {
    id: 'sign1',
    x: 96,
    y: 35,
    name: 'Road sign',
    text: 'The carved letters are worn smooth, but travelers still pause here to rest.',
  },
  {
    id: 'sign2',
    x: 94,
    y: 67,
    name: 'Road sign',
    text: 'Old road markers like this one predate the Sundering, or so the elders say.',
  },
  {
    id: 'sign3',
    x: 98,
    y: 48,
    name: 'Road sign',
    text: 'A crude arrow points onward, its destination lost to weather.',
  },
  {
    id: 'sign4',
    x: 73,
    y: 80,
    name: 'Road sign',
    text: 'Someone has carved a small ember-rune into the post, for luck.',
  },
  {
    id: 'sign5',
    x: 117,
    y: 72,
    name: 'Road sign',
    text: 'The sign creaks in the wind. Its message: safe travels, stranger.',
  },
];
const FARM_PATCHES = [
  { id: 'farm1', x: 44, y: 51, name: 'Farm patch' },
  { id: 'farm2', x: 46, y: 51, name: 'Farm patch' },
  { id: 'farm3', x: 48, y: 51, name: 'Farm patch' },
  { id: 'farm4', x: 57, y: 51, name: 'Farm patch' },
  { id: 'farm5', x: 59, y: 51, name: 'Farm patch' },
  { id: 'farm6', x: 61, y: 51, name: 'Farm patch' },
];
const DUNGEON_CHEST = { x: 22, y: 86, name: 'Warden chest' };
// The Ashen Barrow is a 3x3 grid of chambers (cells 0-8, row-major). Cell 0 is the entrance,
// cell 8 always holds the Warden. BARROW_DOORS lists every possible connection between adjacent
// cells; each Barrow run picks a random unlock order through cells 1-7 (see generateBarrowOrder in
// game1.js), so a different random subset/sequence of these doors opens each time, but the run
// always ends by reaching cell 8.
const BARROW_DOORS = [
  { x: 12, y: 73, a: 0, b: 1 },
  { x: 19, y: 73, a: 1, b: 2 },
  { x: 12, y: 80, a: 3, b: 4 },
  { x: 19, y: 80, a: 4, b: 5 },
  { x: 12, y: 87, a: 6, b: 7 },
  { x: 19, y: 87, a: 7, b: 8 },
  { x: 8, y: 77, a: 0, b: 3 },
  { x: 8, y: 84, a: 3, b: 6 },
  { x: 15, y: 77, a: 1, b: 4 },
  { x: 15, y: 84, a: 4, b: 7 },
  { x: 23, y: 77, a: 2, b: 5 },
  { x: 23, y: 84, a: 5, b: 8 },
];
// One required kill per chamber (cells 0-7); cell 8 is the Warden's chamber and has no entry here.
const BARROW_ROOMS = [
  { cell: 0, kind: 'guardian', x: 9, y: 74 },
  { cell: 1, kind: 'guardian', x: 15, y: 73 },
  { cell: 2, kind: 'guardian', x: 24, y: 73 },
  { cell: 3, kind: 'skeleton', x: 9, y: 80 },
  { cell: 4, kind: 'guardian', x: 15, y: 80 },
  { cell: 5, kind: 'bat', x: 24, y: 80 },
  { cell: 6, kind: 'spider', x: 9, y: 87 },
  { cell: 7, kind: 'guardian', x: 15, y: 87 },
];
const BARROW_TABLETS = [
  {
    id: 'oath',
    x: 17,
    y: 75,
    name: 'Tablet of the Oath',
    text: 'FIRST SEAL — THE OATH. We could not slay the fire, for fire is not slain; it is only kept. So we swore the Oath of Ash: to hold this door though kingdoms rise and fall above us, though our names are forgotten, though we become the very thing we guard. We bound the ember below not to protect the kingdom, but to protect the kingdom from what it would make of us.',
  },
  {
    id: 'watch',
    x: 22,
    y: 82,
    name: 'Tablet of the Watch',
    text: 'SECOND SEAL — THE WATCH. One of us must never sleep. We gave the eldest to the dark, unmade his death, and set him at the door as the Ashen Warden. He will not wake, nor stir, nor strike — unless the seal is broken and the eastern bell falls silent. Should you ever meet him and live, know that the door is already opening.',
  },
  {
    id: 'cinder',
    x: 6,
    y: 82,
    name: 'Tablet of Cinders',
    text: 'THIRD SEAL — THE CINDERS. We gave our lives to the last seal, and our lives became a key, and the key became a relic, and the relic became this door. Three seals, one relic, one door. No living hand may carry the relic into daylight — save one of our own blood, who alone can bear it and not be burned. Pray such a one is never needed. Pray harder that they come.',
  },
];
const TREES = [
  { id: 'tree1', x: 86, y: 81, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree2', x: 108, y: 81, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree3', x: 119, y: 68, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree4', x: 120, y: 69, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree5', x: 119, y: 66, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree6', x: 165, y: 80, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree7', x: 120, y: 49, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree8', x: 70, y: 63, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree9', x: 71, y: 63, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree10', x: 71, y: 59, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree11', x: 68, y: 60, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree12', x: 73, y: 62, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree13', x: 137, y: 47, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree14', x: 142, y: 48, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree15', x: 137, y: 51, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree16', x: 140, y: 52, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree17', x: 135, y: 49, name: 'Tree', level: 1, xp: 14 },
  { id: 'tree18', x: 127, y: 3, name: 'Tree', level: 1, xp: 14 },
];
const FLETCH_RECIPES = [
  {
    id: 'arrows',
    name: 'Carve 15 bronze arrows',
    needs: { logs: 1 },
    makes: 'arrows',
    qty: 15,
    level: 1,
    xp: 20,
  },
  {
    id: 'shortbow',
    name: 'Fletch a shortbow',
    needs: { logs: 2 },
    makes: 'shortbow',
    qty: 1,
    level: 4,
    xp: 42,
  },
];
const HERB_RECIPES = [
  {
    id: 'antidote',
    name: 'Brew marsh antidote',
    needs: { bogMoss: 2, vial: 1 },
    makes: 'antidote',
    qty: 1,
    level: 2,
    xp: 32,
  },
  {
    id: 'healingPotion',
    name: 'Brew minor healing potion',
    needs: { herb: 1, vial: 1 },
    makes: 'healingPotion',
    qty: 1,
    level: 1,
    xp: 25,
  },
  {
    id: 'energyPotion',
    name: 'Brew run energy potion',
    needs: { herb: 2, vial: 1 },
    makes: 'energyPotion',
    qty: 1,
    level: 3,
    xp: 45,
  },
];
const CRAFT_RECIPES = [
  {
    id: 'furGloves',
    name: 'Sew rabbit-fur gloves',
    needs: { rabbitFur: 3 },
    makes: 'furGloves',
    qty: 1,
    level: 3,
    xp: 40,
  },
  {
    id: 'leatherBody',
    name: 'Sew leather body',
    needs: { hide: 3 },
    makes: 'leatherBody',
    qty: 1,
    level: 1,
    xp: 35,
  },
  {
    id: 'silkRobe',
    name: 'Weave cave-silk robe',
    needs: { spiderSilk: 3 },
    makes: 'silkRobe',
    qty: 1,
    level: 5,
    xp: 60,
  },
];
const RECIPES = [
  {
    id: 'bronzeBar',
    name: 'Smelt bronze bar',
    needs: { copperOre: 2 },
    makes: 'bronzeBar',
    qty: 1,
    level: 1,
    xp: 18,
    station: 'furnace',
  },
  {
    id: 'ironBar',
    name: 'Smelt iron bar',
    needs: { ironOre: 2 },
    makes: 'ironBar',
    qty: 1,
    level: 5,
    xp: 30,
    station: 'furnace',
  },
  { id: 'steelBar', name: 'Smelt steel bar', needs: { ironOre: 1, coal: 2 }, makes: 'steelBar', qty: 1, level: 10, xp: 35, station: 'furnace' },
  { id: 'mithrilBar', name: 'Smelt mithril bar', needs: { mithrilOre: 1, coal: 4 }, makes: 'mithrilBar', qty: 1, level: 20, xp: 60, station: 'furnace' },
  {
    id: 'bronzeSword',
    name: 'Forge bronze sword',
    needs: { bronzeBar: 1 },
    makes: 'sword',
    qty: 1,
    level: 1,
    xp: 20,
    station: 'anvil',
  },
  {
    id: 'bronzeShield',
    name: 'Forge bronze shield',
    needs: { bronzeBar: 2 },
    makes: 'shield',
    qty: 1,
    level: 2,
    xp: 25,
    station: 'anvil',
  },
  {
    id: 'bronzeArmor',
    name: 'Forge bronze platebody',
    needs: { bronzeBar: 3 },
    makes: 'bronzeArmor',
    qty: 1,
    level: 3,
    xp: 35,
    station: 'anvil',
  },
  { id: 'bronzeHelmet', name: 'Forge bronze helmet', needs: { bronzeBar: 1 }, makes: 'bronzeHelmet', qty: 1, level: 1, xp: 15, station: 'anvil' },
  { id: 'bronzeLegs', name: 'Forge bronze platelegs', needs: { bronzeBar: 2 }, makes: 'bronzeLegs', qty: 1, level: 2, xp: 22, station: 'anvil' },
  { id: 'ironHelmet', name: 'Forge iron helmet', needs: { ironBar: 2 }, makes: 'ironHelmet', qty: 1, level: 6, xp: 40, station: 'anvil' },
  { id: 'ironLegs', name: 'Forge iron platelegs', needs: { ironBar: 3 }, makes: 'ironLegs', qty: 1, level: 9, xp: 60, station: 'anvil' },
  { id: 'ironShield', name: 'Forge iron kiteshield', needs: { ironBar: 3 }, makes: 'ironShield', qty: 1, level: 7, xp: 50, station: 'anvil' },
  {
    id: 'forgedSword',
    name: 'Forge iron longsword',
    needs: { ironBar: 3 },
    makes: 'forgedSword',
    qty: 1,
    level: 8,
    xp: 55,
    station: 'anvil',
  },
  {
    id: 'ironArmor',
    name: 'Forge iron platebody',
    needs: { ironBar: 5 },
    makes: 'ironArmor',
    qty: 1,
    level: 12,
    xp: 90,
    station: 'anvil',
  },
  { id: 'ironDagger', name: 'Forge iron dagger', needs: { ironBar: 1 }, makes: 'ironDagger', qty: 1, level: 5, xp: 30, station: 'anvil' },
  { id: 'steelGauntlets', name: 'Forge steel gauntlets', needs: { steelBar: 2 }, makes: 'steelGauntlets', qty: 1, level: 11, xp: 60, station: 'anvil' },
  { id: 'steelLongsword', name: 'Forge steel longsword', needs: { steelBar: 2 }, makes: 'steelLongsword', qty: 1, level: 12, xp: 70, station: 'anvil' },
  { id: 'steelKite', name: 'Forge steel kiteshield', needs: { steelBar: 3 }, makes: 'steelKite', qty: 1, level: 13, xp: 85, station: 'anvil' },
  { id: 'steelBattleaxe', name: 'Forge steel battleaxe', needs: { steelBar: 3 }, makes: 'steelBattleaxe', qty: 1, level: 14, xp: 90, station: 'anvil' },
  { id: 'steelPlatebody', name: 'Forge steel platebody', needs: { steelBar: 5 }, makes: 'steelPlatebody', qty: 1, level: 16, xp: 120, station: 'anvil' },
  { id: 'mithrilScimitar', name: 'Forge mithril scimitar', needs: { mithrilBar: 2 }, makes: 'mithrilScimitar', qty: 1, level: 22, xp: 130, station: 'anvil' },
  { id: 'mithrilKite', name: 'Forge mithril kiteshield', needs: { mithrilBar: 3 }, makes: 'mithrilKite', qty: 1, level: 24, xp: 160, station: 'anvil' },
  { id: 'mithrilPlatebody', name: 'Forge mithril platebody', needs: { mithrilBar: 5 }, makes: 'mithrilPlatebody', qty: 1, level: 26, xp: 200, station: 'anvil' },
  { id: 'emberGreatsword', name: 'Forge emberforged greatsword', needs: { emberIngot: 2, mithrilBar: 3 }, makes: 'emberGreatsword', qty: 1, level: 30, xp: 400, station: 'anvil' },
  { id: 'emberTower', name: 'Forge emberforged tower shield', needs: { emberIngot: 2, mithrilBar: 3 }, makes: 'emberTower', qty: 1, level: 30, xp: 400, station: 'anvil' },
  { id: 'emberPlatebody', name: 'Forge emberforged platebody', needs: { emberIngot: 3, mithrilBar: 4 }, makes: 'emberPlatebody', qty: 1, level: 32, xp: 500, station: 'anvil' },
];
const QUESTS = [
  {
    name: 'A Wanderer in Greenrest',
    giver: 'elowen',
    steps: [
      'Speak with Guide Elowen — you woke in the Vale with no memory of who you are',
      'Buy a fishing rod and 3 bait from Fisher Murphy',
      'Catch a riverfish at the western docks (click the rippling water)',
      'Cook the fish at the town range',
      'Defeat a goblin raider driven down from the wastes',
      'Return to Elowen — she says the old tablets glowed the night you arrived',
    ],
    reward: '100 coins, 500 Attack XP, 500 Fishing XP, and 500 Cooking XP',
  },
  {
    name: 'Shadows Over Pineholt',
    giver: 'rowan',
    steps: [
      'Travel north to Pineholt and speak with Captain Rowan of the old watch',
      'Cull 3 goblin raiders and take their hides',
      'Bring the hides to Captain Rowan',
      'Travel west to Cinderforge and speak with Scholar Mira, last of the Warden loremasters',
    ],
    reward: 'Pineholt blade and 120 coins',
  },
  {
    name: 'Beneath the Ashen Barrow',
    giver: 'mira',
    steps: [
      'Speak with Scholar Mira — she believes the Ember answers to your blood',
      'Defeat the Barrow guardian at the Ashfall ruins and recover the seal-key',
      'Descend into the Ashen Barrow, where the living fire lies bound',
      'Face the Ashen Warden, who gave himself to hold the door shut',
      'Return the Ember relic to Scholar Mira',
    ],
    reward: '300 coins and 200 Attack XP',
  },
  {
    name: "The Ashwright's Gambit",
    giver: 'king',
    steps: [
      'Speak with King Aldric — caravans of ember-rune and ore are vanishing near the Ashfall Wastes',
      'Ask around Greenrest — Torren, Alaric, and Captain Rowan may have noticed something',
      'Report what you have learned to Steward Yara in the castle',
      'Follow the tracks into the far northwest wastes and find the hidden camp',
      'Harker will not talk without supplies — bring him what he needs',
      'Follow Harker\'s directions and defeat Ashwright Renn, who guards the camp',
      'Confront Kessa at the heart of the camp',
      'Defeat the Unbound Construct the failing extraction unleashes',
      'Return to King Aldric with word of what you found',
    ],
    reward: '400 coins and 250 Attack XP',
  },
];
const PORTALS = [
  { x: 9, y: 64, toX: 6, toY: 72, label: 'Enter Ashen Barrow' },
  { x: 6, y: 75, toX: 9, toY: 64, label: 'Climb to surface' },
];

const DISCOVERY_REGIONS = [
  'Greenrest Vale',
  'Pineholt',
  'Frostmere',
  'Thornwood',
  'Cinderforge',
  'Sablemarsh',
  'Ashfall Wastes',
];
