const TILE = 32,
  MAP_W = 192,
  MAP_H = 160,
  TICK_MS = 600;
const ITEMS = {
  coins: { name: 'Coins', icon: '\u25CF', stack: true },
  bread: { name: 'Bread', icon: '\u25B0', heal: 4 },
  stew: { name: 'Pineholt stew', icon: '\u25D2', stack: true, heal: 9 },
  rod: { name: 'Fishing rod', icon: '\u2301' },
  bait: { name: 'Fishing bait', icon: '\u2022', stack: true },
  rawFish: { name: 'Raw riverfish', icon: '\u25D6', stack: true },
  rawEel: { name: 'Raw marsh eel', icon: '\u2248', stack: true },
  marshEel: { name: 'Cooked marsh eel', icon: '\u223F', stack: true, heal: 8, cure: 2 },
  rawMeat: { name: 'Raw boar meat', icon: '\u25D3', stack: true },
  cookedMeat: { name: 'Cooked boar meat', icon: '\u25D1', stack: true, heal: 7 },
  snare: { name: 'Wooden snare', icon: '\u2311' },
  rabbitMeat: { name: 'Raw rabbit', icon: '\u25D4', stack: true },
  roastRabbit: { name: 'Roast rabbit', icon: '\u25D5', stack: true, heal: 8 },
  rabbitFur: { name: 'Rabbit fur', icon: '\u224B', stack: true },
  fish: { name: 'Cooked riverfish', icon: '\u25D7', stack: true, heal: 6 },
  bones: { name: 'Bones', icon: 'X', stack: true },
  hide: { name: 'Goblin hide', icon: '\u25C6', stack: true },
  sword: { name: 'Bronze sword', icon: '\u2020', attack: 2 },
  shortbow: { name: 'Shortbow', icon: ')', ranged: 3, range: 5 },
  arrows: { name: 'Bronze arrows', icon: '\u2192', stack: true },
  emberStaff: { name: 'Ember staff', icon: '\u0192', magic: 3, range: 6 },
  emberRune: { name: 'Ember rune', icon: '\u2727', stack: true },
  steelSword: { name: 'Pineholt blade', icon: '\u2021', attack: 4 },
  pickaxe: { name: 'Bronze pickaxe', icon: '\u2692' },
  ironPickaxe: { name: 'Iron pickaxe', icon: '\u26CF' },
  hatchet: { name: 'Bronze hatchet', icon: '\u2320' },
  knife: { name: 'Carving knife', icon: '\u25B6' },
  tinderbox: { name: 'Tinderbox', icon: '\u25A4' },
  copperOre: { name: 'Copper ore', icon: '\u25CF', stack: true },
  ironOre: { name: 'Iron ore', icon: '\u25CF', stack: true },
  bronzeBar: { name: 'Bronze bar', icon: '\u25AC', stack: true },
  ironBar: { name: 'Iron bar', icon: '\u25AC', stack: true },
  forgedSword: { name: 'Iron longsword', icon: '\u2020', attack: 5 },
  shield: { name: 'Bronze shield', icon: '\u25D0', defence: 2, slot: 'shield' },
  roadBuckler: { name: 'Frostmere buckler', icon: '\u25D2', defence: 3, slot: 'shield' },
  ironArmor: { name: 'Iron platebody', icon: '\u25A3', defence: 4, slot: 'armor' },
  leatherBody: { name: 'Leather body', icon: '\u25A7', defence: 3, slot: 'armor' },
  silkRobe: { name: 'Cave-silk robe', icon: '\u25A8', defence: 3, slot: 'armor' },
  wardenCloak: { name: 'Warden cloak', icon: '\u2666', defence: 6, slot: 'armor' },
  willowMantle: { name: 'Thornwood mantle', icon: '\u2660', defence: 4, slot: 'armor' },
  furGloves: { name: 'Rabbit-fur gloves', icon: '\u222A', defence: 2, slot: 'gloves' },
  logs: { name: 'Logs', icon: '\u25A5', stack: true },
  cabbageSeed: { name: 'Cabbage seed', icon: '\u2022', stack: true },
  cabbage: { name: 'Cabbage', icon: '\u25C9', stack: true, heal: 3 },
  herb: { name: 'Wild herb', icon: '\u2663', stack: true },
  vial: { name: 'Empty vial', icon: '\u25C7', stack: true },
  healingPotion: { name: 'Minor healing potion', icon: '\u25C8', stack: true, heal: 8 },
  energyPotion: { name: 'Run energy potion', icon: '\u25C9', stack: true, energy: 35 },
  key: { name: 'Barrow key', icon: '\u26BF' },
  relic: { name: 'Ember relic', icon: '\u2726' },
  ashenShard: { name: 'Ashen shard', icon: '\u2725', stack: true },
  ashenGuard: { name: 'Ashen guard', icon: '\u25D0', defence: 5, slot: 'shield' },
  barrowLantern: { name: 'Barrow lantern', icon: '\u2600' },
  bogMoss: { name: 'Bog moss', icon: '\u2663', stack: true },
  antidote: { name: 'Marsh antidote', icon: '\u25C8', stack: true },
  mireCharm: { name: 'Sablemarsh charm', icon: '\u222A', defence: 3, slot: 'gloves' },
  explorerCape: { name: 'Emberfall explorer cape', icon: '\u2666', defence: 5, slot: 'armor' },
  spiderSilk: { name: 'Cave silk', icon: '\u2318', stack: true },
  // --- Combat depth: smithing materials ---
  coal: { name: 'Coal', icon: '\u25cf', stack: true },
  mithrilOre: { name: 'Mithril ore', icon: '\u25cf', stack: true },
  steelBar: { name: 'Steel bar', icon: '\u25ac', stack: true },
  mithrilBar: { name: 'Mithril bar', icon: '\u25ac', stack: true },
  emberIngot: { name: 'Emberforged ingot', icon: '\u2726', stack: true },
  // --- Tiered weapons (speed = ticks per attack; req = level to wield) ---
  ironDagger: { name: 'Iron dagger', icon: '\u2020', attack: 3, speed: 2, req: 5, reqSkill: 'Attack', spec: 'double' },
  steelLongsword: { name: 'Steel longsword', icon: '\u2020', attack: 7, speed: 4, req: 10, reqSkill: 'Attack' },
  steelBattleaxe: { name: 'Steel battleaxe', icon: '\u2352', attack: 9, speed: 6, req: 12, reqSkill: 'Attack', spec: 'power' },
  mithrilScimitar: { name: 'Mithril scimitar', icon: '\u2021', attack: 11, speed: 3, req: 20, reqSkill: 'Attack', spec: 'double' },
  emberGreatsword: { name: 'Emberforged greatsword', icon: '\u2352', attack: 16, speed: 6, req: 30, reqSkill: 'Attack', spec: 'power' },
  // --- Tiered armour ---
  steelPlatebody: { name: 'Steel platebody', icon: '\u25a3', defence: 6, slot: 'armor', req: 10, reqSkill: 'Defence' },
  mithrilPlatebody: { name: 'Mithril platebody', icon: '\u25a3', defence: 8, slot: 'armor', req: 20, reqSkill: 'Defence' },
  emberPlatebody: { name: 'Emberforged platebody', icon: '\u25a3', defence: 11, slot: 'armor', req: 30, reqSkill: 'Defence' },
  // --- Tiered shields ---
  steelKite: { name: 'Steel kiteshield', icon: '\u25d0', defence: 5, slot: 'shield', req: 10, reqSkill: 'Defence' },
  mithrilKite: { name: 'Mithril kiteshield', icon: '\u25d0', defence: 7, slot: 'shield', req: 20, reqSkill: 'Defence' },
  emberTower: { name: 'Emberforged tower shield', icon: '\u25d0', defence: 10, slot: 'shield', req: 30, reqSkill: 'Defence' },
  // --- Gloves ---
  steelGauntlets: { name: 'Steel gauntlets', icon: '\u222a', defence: 4, slot: 'gloves', req: 10, reqSkill: 'Defence' },
};
// Attack speed + wield requirements for the original weapons/armour
Object.assign(ITEMS.sword, { speed: 4, req: 1, reqSkill: 'Attack' });
Object.assign(ITEMS.steelSword, { speed: 4, req: 5, reqSkill: 'Attack', spec: 'power' });
Object.assign(ITEMS.forgedSword, { speed: 4, req: 10, reqSkill: 'Attack' });
Object.assign(ITEMS.shortbow, { speed: 4, req: 1, reqSkill: 'Ranged' });
Object.assign(ITEMS.emberStaff, { speed: 5, req: 1, reqSkill: 'Magic' });
Object.assign(ITEMS.shield, { req: 1, reqSkill: 'Defence' });
Object.assign(ITEMS.roadBuckler, { req: 5, reqSkill: 'Defence' });
Object.assign(ITEMS.ironArmor, { req: 10, reqSkill: 'Defence' });
Object.assign(ITEMS.leatherBody, { req: 1, reqSkill: 'Defence' });
Object.assign(ITEMS.silkRobe, { req: 1, reqSkill: 'Defence' });
Object.assign(ITEMS.willowMantle, { req: 8, reqSkill: 'Defence' });
Object.assign(ITEMS.wardenCloak, { req: 20, reqSkill: 'Defence' });
Object.assign(ITEMS.ashenGuard, { req: 15, reqSkill: 'Defence' });
Object.assign(ITEMS.explorerCape, { req: 10, reqSkill: 'Defence' });
Object.entries({
  bread: 3,
  stew: 7,
  rod: 12,
  bait: 1,
  rawFish: 2,
  rawEel: 5,
  marshEel: 13,
  rawMeat: 4,
  cookedMeat: 9,
  snare: 18,
  rabbitMeat: 5,
  roastRabbit: 11,
  rabbitFur: 8,
  fish: 5,
  bones: 1,
  hide: 8,
  sword: 22,
  shortbow: 32,
  arrows: 1,
  emberStaff: 40,
  emberRune: 2,
  steelSword: 60,
  pickaxe: 18,
  ironPickaxe: 60,
  hatchet: 15,
  knife: 12,
  tinderbox: 5,
  copperOre: 3,
  ironOre: 7,
  bronzeBar: 8,
  ironBar: 18,
  forgedSword: 90,
  shield: 30,
  roadBuckler: 85,
  ironArmor: 110,
  leatherBody: 70,
  silkRobe: 95,
  wardenCloak: 250,
  willowMantle: 140,
  furGloves: 65,
  logs: 3,
  cabbageSeed: 2,
  cabbage: 4,
  herb: 6,
  vial: 2,
  healingPotion: 22,
  energyPotion: 28,
  ashenShard: 30,
  ashenGuard: 420,
  barrowLantern: 300,
  bogMoss: 12,
  antidote: 30,
  mireCharm: 120,
  explorerCape: 350,
  spiderSilk: 10,
  coal: 5,
  mithrilOre: 35,
  steelBar: 25,
  mithrilBar: 55,
  emberIngot: 200,
  ironDagger: 40,
  steelLongsword: 120,
  steelBattleaxe: 180,
  mithrilScimitar: 320,
  emberGreatsword: 1200,
  steelPlatebody: 200,
  mithrilPlatebody: 450,
  emberPlatebody: 1400,
  steelKite: 160,
  mithrilKite: 380,
  emberTower: 1100,
  steelGauntlets: 120,
}).forEach(([id, value]) => (ITEMS[id].value = value));
const NPCS = [
  { id: 'elowen', name: 'Guide Elowen', x: 96, y: 124, color: '#c5a44e', role: 'Greenrest guide' },
  { id: 'alaric', name: 'Alaric', x: 103, y: 127, color: '#a86c3d', role: 'General store trader' },
  { id: 'murphy', name: 'Fisher Murphy', x: 82, y: 124, color: '#4f83a4', role: 'Fishing supplier' },
  { id: 'banker', name: 'Banker Willa', x: 87, y: 126, color: '#795b9b', role: 'Greenrest bank' },
  { id: 'rowan', name: 'Captain Rowan', x: 87, y: 66, color: '#8f4d3f', role: 'Pineholt watch-captain' },
  { id: 'tamsin', name: 'Tamsin', x: 104, y: 66, color: '#b77943', role: 'Pineholt innkeeper' },
  {
    id: 'fen',
    name: 'Bard Fen',
    x: 99,
    y: 73,
    color: '#6f568c',
    role: 'Travelling bard',
    wander: 2,
    dialogue:
      'Every road remembers its travellers. The Ashen Barrow song has gained a new verse since you arrived.',
  },
  { id: 'mira', name: 'Scholar Mira', x: 164, y: 130, color: '#665ca5', role: 'Warden loremaster' },
  { id: 'torren', name: 'Torren', x: 149, y: 130, color: '#6f7f8f', role: 'Emberwright smith' },
  {
    id: 'bren',
    name: 'Guard Bren',
    x: 99,
    y: 130,
    color: '#687b8d',
    role: 'Greenrest guard',
    wander: 3,
    dialogue:
      'The seals below weaken, and the wastes spill their creatures over the land. I pay good coin for every beast you put down — call it keeping the old watch.',
  },
  {
    id: 'jory',
    name: 'Farmer Jory',
    x: 92,
    y: 140,
    color: '#8b7042',
    role: 'Greenrest farmer',
    wander: 4,
    pickpocket: true,
    dialogue: 'The vale fields feed the whole region. Mind the wolves up in the pines.',
  },
  {
    id: 'nessa',
    name: 'Nessa',
    x: 94,
    y: 72,
    color: '#a16d78',
    role: 'Pineholt villager',
    wander: 3,
    pickpocket: true,
    dialogue:
      "Captain Rowan's line has watched the north road since the Binding. We sleep easier for it — most nights.",
  },
  { id: 'willow', name: 'Elder Willow', x: 147, y: 70, color: '#7c9760', role: 'Thornwood elder' },
  { id: 'orin', name: 'Hunter Orin', x: 162, y: 70, color: '#806348', role: 'Thornwood hunter' },
  {
    id: 'maeve',
    name: 'Maeve',
    x: 153,
    y: 73,
    color: '#7996a2',
    role: 'Thornwood villager',
    wander: 3,
    pickpocket: true,
    dialogue:
      'The boars root near the eastern hedges. Orin pays attention to anyone carrying a bow.',
  },
  {
    id: 'vale',
    name: 'Scout Vale',
    x: 42,
    y: 52,
    color: '#557c68',
    role: 'Warden watcher',
    wander: 3,
    pickpocket: true,
    dialogue:
      'I watch the Barrow door so the world need not. The ruins glow after sunset now — the seal is thinning, and I am the last set to watch it.',
  },
  { id: 'mara', name: 'Mara', x: 88, y: 20, color: '#a36f45', role: 'Frostmere provisioner' },
  {
    id: 'edric',
    name: 'Brother Edric',
    x: 104,
    y: 20,
    color: '#8a7aa3',
    role: 'Frostmere healer',
    dialogue: 'Every traveller deserves a warm fire before crossing the snowfields.',
  },
  { id: 'sable', name: 'Healer Sable', x: 31, y: 128, color: '#56806a', role: 'Sablemarsh healer' },
  {
    id: 'fenwick',
    name: 'Fenwick',
    x: 43,
    y: 128,
    color: '#8a6d47',
    role: 'Sablemarsh trader',
    dialogue: 'Dry boots cost extra in Sablemarsh. Everything else is fairly priced.',
  },
];
const NPC_AMBIENT = {
  elowen: [
    'The Vale is the green heart — farthest from the wound below.',
    'You arrived the night the old tablets glowed. That was not chance.',
  ],
  alaric: [
    'Supplies for the wastes road, friend — you will need them.',
    'My gran swore the sky once burned. I used to laugh at her.',
  ],
  murphy: [
    'The water tastes of ash some mornings now. Never used to.',
    'Even the fish feel it stirring, down under the earth.',
  ],
  rowan: [
    'My line has watched this northern road since the Binding.',
    'Things climb down out of the Ashfall. Keep your blade near.',
  ],
  tamsin: [
    'Warm beds and warmer stew — small mercies while the seals hold.',
    'Sing an old Barrow verse and the hearth burns brighter, they say.',
  ],
  bren: [
    'The failing seals loose what I pay good folk to cull.',
    'Contracts for capable hands — the wastes breed more each week.',
  ],
  jory: [
    'Good soil, so long as the ash stays north of my fences.',
    'The wolves come down from the pines, fleeing something worse.',
  ],
  willow: [
    'The three tablets survive here as ballads. Listen close.',
    'The Wardens gave everything they were to shut that door.',
  ],
  orin: [
    'I track beasts that flee the ash into my woods.',
    'Aim true — the prey runs angrier than it once did.',
  ],
  maeve: [
    'Boars root by the hedge, running from the wastes.',
    'They say the fire below is waking. I try not to dwell on it.',
  ],
  mira: [
    'The Barrow runes are changing. The seals are weakening.',
    'You are ember-touched, Wanderer. The old Warden blood, I am nearly sure.',
  ],
  torren: [
    'Ember-heat forges the finest steel — and the mountain gives more each day.',
    'Cinderforge sits closest to the buried fire. We feel every tremor.',
  ],
  vale: [
    'The Barrow ruins glow after sunset. The seal is thinning.',
    'I watch the door so the rest of the world need not.',
  ],
  mara: [
    "The cold holds the Ember's heat at bay — for now.",
    'Provisions before the snowfields, traveller. Frostmere endures.',
  ],
  edric: [
    'I say the prayers that the three seals hold another year.',
    'A warm fire, and a word for the Wardens who gave theirs.',
  ],
  sable: [
    "The marsh-fever is the Ember's sickness, seeping up through the water.",
    'Bog moss dulls the ache. A true cure it is not.',
  ],
  fenwick: [
    'Dry goods in a drowning marsh — and the fever only worsens.',
    'Mind the boglings; they crawl up thicker every season.',
  ],
};
const MONSTER_TYPES = {
  rat: {
    name: 'Giant rat',
    color: '#776753',
    hp: 4,
    maxHit: 1,
    xp: 8,
    drops: [
      ['bones', 1, 1],
      ['coins', 2, 7],
    ],
  },
  goblin: {
    name: 'Goblin raider',
    color: '#678847',
    hp: 8,
    maxHit: 2,
    xp: 14,
    drops: [
      ['bones', 1, 1],
      ['coins', 5, 14],
      ['hide', 1, 1],
      ['herb', 1, 1, 0.25],
      ['emberRune', 1, 3, 0.4],
    ],
  },
  wolf: {
    name: 'Grey wolf',
    color: '#66727a',
    hp: 11,
    maxHit: 2,
    xp: 18,
    drops: [
      ['bones', 1, 1],
      ['coins', 6, 15],
      ['herb', 1, 1, 0.3],
    ],
  },
  skeleton: {
    name: 'Barrow skeleton',
    color: '#c9c3a4',
    hp: 13,
    maxHit: 3,
    xp: 24,
    drops: [
      ['bones', 1, 2],
      ['coins', 8, 20],
      ['emberRune', 2, 5, 0.55],
    ],
  },
  guardian: {
    name: 'Barrow guardian',
    color: '#d4c99f',
    hp: 16,
    maxHit: 3,
    xp: 30,
    drops: [
      ['bones', 1, 2],
      ['coins', 12, 24],
      ['emberRune', 3, 6, 0.65],
    ],
  },
  boar: {
    name: 'Wild boar',
    color: '#7b543e',
    hp: 9,
    maxHit: 2,
    xp: 16,
    drops: [
      ['bones', 1, 1],
      ['coins', 4, 11],
      ['rawMeat', 1, 1, 0.75],
    ],
  },
  bandit: {
    name: 'Road bandit',
    color: '#8a553c',
    hp: 12,
    maxHit: 3,
    xp: 22,
    drops: [
      ['coins', 10, 28],
      ['bread', 1, 2, 0.55],
      ['herb', 1, 1, 0.3],
    ],
  },
  bat: {
    name: 'Ash bat',
    color: '#6e536f',
    hp: 7,
    maxHit: 2,
    xp: 15,
    drops: [
      ['bones', 1, 1],
      ['coins', 3, 10],
      ['emberRune', 1, 2, 0.5],
    ],
  },
  bogling: {
    name: 'Bogling',
    color: '#46684b',
    hp: 10,
    maxHit: 2,
    xp: 19,
    drops: [
      ['bogMoss', 1, 1],
      ['coins', 4, 13],
      ['herb', 1, 1, 0.35],
    ],
  },
  spider: {
    name: 'Cave spider',
    color: '#5a3855',
    hp: 10,
    maxHit: 3,
    xp: 20,
    drops: [
      ['spiderSilk', 1, 2],
      ['coins', 4, 12],
    ],
  },
  warden: {
    name: 'Ashen Warden',
    color: '#8d503d',
    hp: 30,
    maxHit: 4,
    xp: 90,
    drops: [
      ['ashenShard', 1, 2],
      ['coins', 75, 120],
      ['emberIngot', 1, 2, 0.5],
    ],
  },
  direWolf: {
    name: 'Dire wolf',
    color: '#4a525a',
    hp: 20,
    maxHit: 4,
    xp: 40,
    drops: [
      ['bones', 1, 1],
      ['coins', 10, 24],
      ['coal', 1, 3, 0.4],
      ['mithrilOre', 1, 1, 0.12],
    ],
  },
  goblinWarlord: {
    name: 'Goblin warlord',
    color: '#3f6b2c',
    hp: 45,
    maxHit: 5,
    xp: 120,
    boss: true,
    attackSpeed: 3,
    drops: [
      ['coins', 60, 140],
      ['steelBar', 2, 4],
      ['steelLongsword', 1, 1, 0.2],
      ['emberIngot', 1, 1, 0.15],
    ],
  },
  cinderFiend: {
    name: 'Cinder fiend',
    color: '#c0542a',
    hp: 28,
    maxHit: 5,
    xp: 60,
    drops: [
      ['coins', 14, 30],
      ['coal', 2, 4, 0.5],
      ['mithrilOre', 1, 2, 0.2],
      ['emberIngot', 1, 1, 0.1],
    ],
  },
  frostTroll: {
    name: 'Frost troll',
    color: '#7fa3c4',
    hp: 34,
    maxHit: 5,
    xp: 72,
    drops: [
      ['bones', 1, 2],
      ['coins', 18, 36],
      ['mithrilOre', 1, 2, 0.25],
      ['emberIngot', 1, 1, 0.12],
    ],
  },
  cinderColossus: {
    name: 'Cinder Colossus',
    color: '#e0631f',
    hp: 65,
    maxHit: 6,
    xp: 220,
    boss: true,
    attackSpeed: 4,
    drops: [
      ['coins', 150, 300],
      ['emberIngot', 2, 4],
      ['emberGreatsword', 1, 1, 0.12],
      ['emberPlatebody', 1, 1, 0.1],
    ],
  },
};
const MONSTER_SPAWNS = [
  // Frostmere (snow north)
  ['rat', 84, 30],
  ['rat', 110, 28],
  ['wolf', 76, 34],
  // Pineholt (pine highlands)
  ['goblin', 90, 52],
  ['goblin', 104, 52],
  ['goblin', 86, 86],
  ['goblin', 106, 86],
  ['wolf', 82, 52],
  ['wolf', 110, 54],
  ['wolf', 80, 90],
  // Thornwood (woodland)
  ['boar', 144, 90],
  ['boar', 168, 86],
  ['boar', 150, 98],
  // Cinderforge (volcanic)
  ['rat', 140, 118],
  ['bandit', 144, 148],
  ['bandit', 180, 120],
  // Sablemarsh (swamp)
  ['bogling', 18, 140],
  ['bogling', 46, 142],
  ['bogling', 30, 150],
  ['bogling', 14, 132],
  // Ashfall Wastes surface (barrow ruins)
  ['guardian', 36, 54],
  ['guardian', 30, 56],
  ['bandit', 50, 60],
  // Ashen Barrow dungeon (sealed vault)
  ['skeleton', 14, 80],
  ['skeleton', 30, 90],
  ['bat', 12, 88],
  ['bat', 30, 84],
  ['bat', 20, 92],
  ['spider', 28, 80],
  ['spider', 14, 92],
  ['warden', 22, 84],
  // Tougher roaming enemies + mini-bosses
  ['direWolf', 82, 84],
  ['direWolf', 112, 86],
  ['goblinWarlord', 98, 90],
  ['frostTroll', 100, 10],
  ['frostTroll', 120, 30],
  ['cinderFiend', 176, 124],
  ['cinderFiend', 152, 148],
  ['cinderColossus', 182, 148],
];
const SHOPS = {
  general: [
    ['bread', 6],
    ['sword', 45],
    ['shortbow', 65],
    ['arrows', 2],
    ['emberStaff', 80],
    ['emberRune', 3],
    ['shield', 55],
    ['hatchet', 30],
    ['tinderbox', 10],
    ['cabbageSeed', 3],
    ['vial', 4],
  ],
  fishing: [
    ['rod', 20],
    ['bait', 1],
  ],
  hunter: [
    ['snare', 35],
    ['knife', 25],
    ['shortbow', 60],
    ['arrows', 2],
    ['leatherBody', 125],
  ],
  smith: [
    ['pickaxe', 35],
    ['ironPickaxe', 120],
  ],
  mirehaven: [
    ['bread', 5],
    ['vial', 3],
    ['herb', 8],
    ['antidote', 32],
    ['healingPotion', 24],
    ['energyPotion', 30],
    ['tinderbox', 8],
  ],
  embercross: [
    ['bread', 5],
    ['stew', 10],
    ['healingPotion', 25],
    ['energyPotion', 32],
    ['emberRune', 3],
    ['vial', 3],
  ],
};
const FISH_SPOTS = [
  {
    id: 'heartwoodFish',
    x: 78,
    y: 124,
    name: 'River fishing spot',
    item: 'rawFish',
    catchName: 'riverfish',
    level: 1,
    xp: 12,
    chance: 0.8,
  },
  {
    id: 'mireEel',
    x: 24,
    y: 132,
    name: 'Marsh eel spot',
    item: 'rawEel',
    catchName: 'marsh eel',
    level: 3,
    xp: 22,
    chance: 0.72,
  },
];
const HUNT_SPOTS = [
  { id: 'burrow1', x: 140, y: 80, name: 'Rabbit burrow', level: 1, xp: 20 },
  { id: 'burrow2', x: 166, y: 82, name: 'Rabbit burrow', level: 1, xp: 20 },
];
const ROCKS = [
  {
    id: 'copper1',
    x: 170,
    y: 116,
    ore: 'copperOre',
    name: 'Copper rock',
    level: 1,
    xp: 12,
    color: '#b87343',
  },
  {
    id: 'copper2',
    x: 172,
    y: 119,
    ore: 'copperOre',
    name: 'Copper rock',
    level: 1,
    xp: 12,
    color: '#b87343',
  },
  {
    id: 'iron1',
    x: 168,
    y: 138,
    ore: 'ironOre',
    name: 'Iron rock',
    level: 5,
    xp: 22,
    color: '#8d8174',
  },
  {
    id: 'iron2',
    x: 150,
    y: 138,
    ore: 'ironOre',
    name: 'Iron rock',
    level: 5,
    xp: 22,
    color: '#8d8174',
  },
  { id: 'coal1', x: 174, y: 114, ore: 'coal', name: 'Coal rock', level: 10, xp: 28, color: '#2c2c2c' },
  { id: 'coal2', x: 164, y: 118, ore: 'coal', name: 'Coal rock', level: 10, xp: 28, color: '#2c2c2c' },
  { id: 'mithril1', x: 178, y: 138, ore: 'mithrilOre', name: 'Mithril rock', level: 20, xp: 55, color: '#4a6b8a' },
  { id: 'mithril2', x: 148, y: 144, ore: 'mithrilOre', name: 'Mithril rock', level: 20, xp: 55, color: '#4a6b8a' },
];
const FORGE = { x: 150, y: 124, name: 'Cinderforge anvil' };
const ALTAR = { x: 104, y: 14, name: 'Frostmere altar' };
const WORKBENCH = { x: 110, y: 128, name: 'Greenrest crafting bench' };
const CAULDRON = { x: 35, y: 130, name: 'Sablemarsh brewing cauldron' };
const SIGNPOSTS = [
  {
    id: 'eastSign',
    x: 140,
    y: 132,
    name: 'Cinderforge road sign',
    text: 'Cinderforge — forge and mines. North: Thornwood. West: Greenrest Vale.',
  },
  {
    id: 'northSign',
    x: 96,
    y: 34,
    name: 'Northern road sign',
    text: 'North: Frostmere Hold. South: Pineholt and Greenrest Vale.',
  },
  {
    id: 'southSign',
    x: 46,
    y: 120,
    name: 'Sablemarsh road sign',
    text: 'Sablemarsh — marsh village. East: Greenrest Vale. North: the Ashfall Wastes.',
  },
  {
    id: 'emberSign',
    x: 44,
    y: 58,
    name: 'Ashfall road sign',
    text: 'Ashfall Wastes. West: the Ashen Barrow. South: Sablemarsh. East: Greenrest Vale.',
  },
];
const FARM_PATCHES = [
  { id: 'heartwood1', x: 90, y: 140, name: 'Farm patch' },
  { id: 'heartwood2', x: 92, y: 140, name: 'Farm patch' },
  { id: 'heartwood3', x: 94, y: 140, name: 'Farm patch' },
];
const DUNGEON_CHEST = { x: 30, y: 80, name: 'Warden chest' };
const DUNGEON_LEVER = { x: 12, y: 92, name: 'Ancient lever', kind: 'dungeonLever' };
const DUNGEON_GATE = { x: 24, y: 86, name: 'Barrow portcullis', kind: 'dungeonGate' };
const BARROW_TABLETS = [
  {
    id: 'oath',
    x: 12,
    y: 82,
    name: 'Tablet of the Oath',
    text: 'FIRST SEAL — THE OATH. We could not slay the fire, for fire is not slain; it is only kept. So we swore the Oath of Ash: to hold this door though kingdoms rise and fall above us, though our names are forgotten, though we become the very thing we guard. We bound the ember below not to protect the kingdom, but to protect the kingdom from what it would make of us.',
  },
  {
    id: 'watch',
    x: 30,
    y: 92,
    name: 'Tablet of the Watch',
    text: 'SECOND SEAL — THE WATCH. One of us must never sleep. We gave the eldest to the dark, unmade his death, and set him at the door as the Ashen Warden. He will not wake, nor stir, nor strike — unless the seal is broken and the eastern bell falls silent. Should you ever meet him and live, know that the door is already opening.',
  },
  {
    id: 'cinder',
    x: 22,
    y: 78,
    name: 'Tablet of Cinders',
    text: 'THIRD SEAL — THE CINDERS. We gave our lives to the last seal, and our lives became a key, and the key became a relic, and the relic became this door. Three seals, one relic, one door. No living hand may carry the relic into daylight — save one of our own blood, who alone can bear it and not be burned. Pray such a one is never needed. Pray harder that they come.',
  },
];
const TREES = [
  { id: 'oak1', x: 112, y: 124, name: 'Vale oak', level: 1, xp: 14 },
  { id: 'oak2', x: 114, y: 127, name: 'Vale oak', level: 1, xp: 14 },
  { id: 'oak3', x: 70, y: 140, name: 'Vale oak', level: 1, xp: 14 },
  { id: 'oak4', x: 86, y: 80, name: 'Pineholt pine', level: 1, xp: 14 },
  { id: 'oak5', x: 108, y: 80, name: 'Pineholt pine', level: 1, xp: 14 },
];
const FLETCH_RECIPES = [
  {
    id: 'arrows',
    name: 'Carve 15 bronze arrows',
    needs: { logs: 1 },
    makes: 'arrows',
    qty: 15,
    level: 1,
    xp: 20,
  },
  {
    id: 'shortbow',
    name: 'Fletch a shortbow',
    needs: { logs: 2 },
    makes: 'shortbow',
    qty: 1,
    level: 4,
    xp: 42,
  },
];
const HERB_RECIPES = [
  {
    id: 'antidote',
    name: 'Brew marsh antidote',
    needs: { bogMoss: 2, vial: 1 },
    makes: 'antidote',
    qty: 1,
    level: 2,
    xp: 32,
  },
  {
    id: 'healingPotion',
    name: 'Brew minor healing potion',
    needs: { herb: 1, vial: 1 },
    makes: 'healingPotion',
    qty: 1,
    level: 1,
    xp: 25,
  },
  {
    id: 'energyPotion',
    name: 'Brew run energy potion',
    needs: { herb: 2, vial: 1 },
    makes: 'energyPotion',
    qty: 1,
    level: 3,
    xp: 45,
  },
];
const CRAFT_RECIPES = [
  {
    id: 'furGloves',
    name: 'Sew rabbit-fur gloves',
    needs: { rabbitFur: 3 },
    makes: 'furGloves',
    qty: 1,
    level: 3,
    xp: 40,
  },
  {
    id: 'leatherBody',
    name: 'Sew leather body',
    needs: { hide: 3 },
    makes: 'leatherBody',
    qty: 1,
    level: 1,
    xp: 35,
  },
  {
    id: 'silkRobe',
    name: 'Weave cave-silk robe',
    needs: { spiderSilk: 3 },
    makes: 'silkRobe',
    qty: 1,
    level: 5,
    xp: 60,
  },
];
const RECIPES = [
  {
    id: 'bronzeBar',
    name: 'Smelt bronze bar',
    needs: { copperOre: 2 },
    makes: 'bronzeBar',
    qty: 1,
    level: 1,
    xp: 18,
  },
  {
    id: 'ironBar',
    name: 'Smelt iron bar',
    needs: { ironOre: 2 },
    makes: 'ironBar',
    qty: 1,
    level: 5,
    xp: 30,
  },
  {
    id: 'forgedSword',
    name: 'Forge iron longsword',
    needs: { ironBar: 3 },
    makes: 'forgedSword',
    qty: 1,
    level: 8,
    xp: 55,
  },
  {
    id: 'ironArmor',
    name: 'Forge iron platebody',
    needs: { ironBar: 5 },
    makes: 'ironArmor',
    qty: 1,
    level: 12,
    xp: 90,
  },
  { id: 'ironDagger', name: 'Forge iron dagger', needs: { ironBar: 1 }, makes: 'ironDagger', qty: 1, level: 5, xp: 30 },
  { id: 'steelBar', name: 'Smelt steel bar', needs: { ironOre: 1, coal: 2 }, makes: 'steelBar', qty: 1, level: 10, xp: 35 },
  { id: 'steelGauntlets', name: 'Forge steel gauntlets', needs: { steelBar: 2 }, makes: 'steelGauntlets', qty: 1, level: 11, xp: 60 },
  { id: 'steelLongsword', name: 'Forge steel longsword', needs: { steelBar: 2 }, makes: 'steelLongsword', qty: 1, level: 12, xp: 70 },
  { id: 'steelKite', name: 'Forge steel kiteshield', needs: { steelBar: 3 }, makes: 'steelKite', qty: 1, level: 13, xp: 85 },
  { id: 'steelBattleaxe', name: 'Forge steel battleaxe', needs: { steelBar: 3 }, makes: 'steelBattleaxe', qty: 1, level: 14, xp: 90 },
  { id: 'steelPlatebody', name: 'Forge steel platebody', needs: { steelBar: 5 }, makes: 'steelPlatebody', qty: 1, level: 16, xp: 120 },
  { id: 'mithrilBar', name: 'Smelt mithril bar', needs: { mithrilOre: 1, coal: 4 }, makes: 'mithrilBar', qty: 1, level: 20, xp: 60 },
  { id: 'mithrilScimitar', name: 'Forge mithril scimitar', needs: { mithrilBar: 2 }, makes: 'mithrilScimitar', qty: 1, level: 22, xp: 130 },
  { id: 'mithrilKite', name: 'Forge mithril kiteshield', needs: { mithrilBar: 3 }, makes: 'mithrilKite', qty: 1, level: 24, xp: 160 },
  { id: 'mithrilPlatebody', name: 'Forge mithril platebody', needs: { mithrilBar: 5 }, makes: 'mithrilPlatebody', qty: 1, level: 26, xp: 200 },
  { id: 'emberGreatsword', name: 'Forge emberforged greatsword', needs: { emberIngot: 2, mithrilBar: 3 }, makes: 'emberGreatsword', qty: 1, level: 30, xp: 400 },
  { id: 'emberTower', name: 'Forge emberforged tower shield', needs: { emberIngot: 2, mithrilBar: 3 }, makes: 'emberTower', qty: 1, level: 30, xp: 400 },
  { id: 'emberPlatebody', name: 'Forge emberforged platebody', needs: { emberIngot: 3, mithrilBar: 4 }, makes: 'emberPlatebody', qty: 1, level: 32, xp: 500 },
];
const QUESTS = [
  {
    name: 'A Wanderer in Greenrest',
    giver: 'elowen',
    steps: [
      'Speak with Guide Elowen — you woke in the Vale with no memory of who you are',
      'Buy a fishing rod and 3 bait from Fisher Murphy',
      'Catch a riverfish at the western docks (click the rippling water)',
      'Cook the fish at the town range',
      'Defeat a goblin raider driven down from the wastes',
      'Return to Elowen — she says the old tablets glowed the night you arrived',
    ],
    reward: '100 coins and 60 Attack XP',
  },
  {
    name: 'Shadows Over Pineholt',
    giver: 'rowan',
    steps: [
      'Travel north to Pineholt and speak with Captain Rowan of the old watch',
      'Cull 3 goblin raiders and take their hides',
      'Bring the hides to Captain Rowan',
      'Travel east to Cinderforge and speak with Scholar Mira, last of the Warden loremasters',
    ],
    reward: 'Pineholt blade and 120 coins',
  },
  {
    name: 'Beneath the Ashen Barrow',
    giver: 'mira',
    steps: [
      'Speak with Scholar Mira — she believes the Ember answers to your blood',
      'Defeat the Barrow guardian at the Ashfall ruins and recover the seal-key',
      'Descend into the Ashen Barrow, where the living fire lies bound',
      'Face the Ashen Warden, who gave himself to hold the door shut',
      'Return the Ember relic to Scholar Mira',
    ],
    reward: '300 coins and 200 Attack XP',
  },
];
const PORTALS = [
  { x: 40, y: 52, toX: 20, toY: 86, label: 'Enter Ashen Barrow' },
  { x: 20, y: 88, toX: 40, toY: 54, label: 'Climb to surface' },
];

const DISCOVERY_REGIONS = [
  'Greenrest Vale',
  'Pineholt',
  'Frostmere',
  'Thornwood',
  'Cinderforge',
  'Sablemarsh',
  'Ashfall Wastes',
];
