const fs = require('fs');
const path = require('path');

const root = process.cwd();
const sourcePath = path.join(root, 'godot', 'data', 'legacy_world.json');
const outputPath = path.join(root, 'godot', 'data', 'world_structures.json');
const editorOutputPath = path.join(root, 'js', 'world_structures.js');
const data = JSON.parse(fs.readFileSync(sourcePath, 'utf8'));
const encoding = '0123456789abcde';
const width = data.width;
const height = data.height;

function tile(x, y) {
  if (x < 0 || y < 0 || x >= width || y >= height) return -1;
  return encoding.indexOf(data.terrain[y * width + x]);
}

function edgeKey(edge) {
  const first = edge.y1 * width + edge.x1;
  const second = edge.y2 * width + edge.x2;
  return first < second ? `${first}:${second}` : `${second}:${first}`;
}

const edges = [];
const keys = new Set();

function addEdge(x1, y1, x2, y2, type) {
  const edge = { x1, y1, x2, y2, type };
  const key = edgeKey(edge);
  if (keys.has(key)) return;
  keys.add(key);
  edges.push(edge);
}

function addHouseWallEdges(x, y) {
  let found = false;
  for (const [dx, dy] of [[-1, 0], [1, 0], [0, -1], [0, 1]]) {
    if ([5, 6, 8].includes(tile(x + dx, y + dy))) {
      addEdge(x, y, x + dx, y + dy, 'wall');
      found = true;
    }
  }
  return found;
}

function addRunEdges(x, y, type, tileType) {
  const horizontal = tile(x - 1, y) === tileType || tile(x + 1, y) === tileType;
  const vertical = tile(x, y - 1) === tileType || tile(x, y + 1) === tileType;

  if (horizontal) addEdge(x, y, x, y - 1, type);
  if (vertical) addEdge(x, y, x - 1, y, type);
  if (!horizontal && !vertical) addEdge(x, y, x, y - 1, type);
}

for (let y = 0; y < height; y++) {
  for (let x = 0; x < width; x++) {
    const value = tile(x, y);
    if (value === 7) {
      addRunEdges(x, y, 'fence', 7);
    } else if (value === 4) {
      if (!addHouseWallEdges(x, y)) addRunEdges(x, y, 'wall', 4);
    }
  }
}

const result = {
  version: 1,
  tile_size: 1.5,
  generated_from: 'legacy_world.json',
  note: 'First-pass conversion. Refine edges in mapeditor.html.',
  edges,
};

fs.writeFileSync(outputPath, `${JSON.stringify(result, null, 2)}\n`);
fs.writeFileSync(
  editorOutputPath,
  `// Generated by tools/generate_world_structures.js\n`
    + `const AUTHORED_STRUCTURE_EDGES = ${JSON.stringify(edges, null, 2)};\n`,
);
console.log(`Generated ${edges.length} structure edges at ${outputPath}`);
